@startuml
left to right direction
package SystemBoundary {
  usecase "Kijelentkezés" as LogOut
  usecase "Művek megtekintése" as Dashboard
  usecase "Művek rendezése" as FilterLogs
  LogOut <. Dashboard : <<extend>>
  Dashboard .> FilterLogs : <<extend>>
  FilterLogs .> Dashboard : <<include>>
}
:Felhasználó: --> Dashboard
:Felhasználó: --> LogOut
:Felhasználó: --> FilterLogs
@enduml
