@startuml
left to right direction

actor :Bejelentkezett \n felhasználó: as LoggedInUser

usecase "Már hozzáadott \n művek között szűrés" as FilterMedia
usecase "Művek szűrésnek \n megfelelő megjelenítése" as DisplayFilteredMedia

LoggedInUser --> FilterMedia
FilterMedia --> DisplayFilteredMedia

@enduml