@startuml
left to right direction

actor :Bejelentkezett \n felhasználó: as LoggedInUser

usecase "Kijelentkezés" as LogOut
usecase "Bejelentkezési képernyő" as LoginScreen

LoggedInUser --> LogOut
LogOut --> LoginScreen

@enduml